name: Build Images

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
jobs:
  build:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host: [
          "ubuntu-latest",
          #"macos-10.15",
        ]
        arch:
          - armhf
          - arm64
    name: 'Build:  ${{ matrix.arch }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run Base Pifile
        uses: Nature40/pimod@v0.2.1
        with:
          pifile: base_${{ matrix.arch }}.Pifile
      - name: Run OpenDsh Pifile
        uses: Nature40/pimod@v0.2.1
        with:
          pifile: opendsh_${{ matrix.arch }}.Pifile
      - 
        name: Get the version
        id: get_version
        run: |
          codename=grep "VERSION=" /etc/os-release |awk -F= {' print $2'}|sed s/\"//g |sed s/[0-9]//g | sed s/\)$//g |sed s/\(//g
          if [ -z "$version" ]
          then
                version=$(date '+%Y%m%d')
                echo ::set-output name=version::"${version}-${codename}-${arch}"
          else
                echo ::set-output name=version::"${version}"
          fi
        env:
          version: ${{ github.event.inputs.version }}
          arch: ${{ matrix.arch }}
      - name: Rename opendsh-${{ matrix.arch }} Image
        run: mv opendsh.img opendsh-${{ steps.get_version.outputs.version }}.img
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.version }}
      - name: Package opendsh-${{ matrix.arch }}.zip
        run: zip opendsh-${{ steps.get_version.outputs.version }}.zip opendsh-${{ steps.get_version.outputs.version }}.img
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.version }}
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.get_version.outputs.version }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: true
          prerelease: true
      - name: Upload opendsh-${{ matrix.arch }}.zip to release
        id: upload_batrack_zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.get_version.outputs.version }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: opendsh-${{ steps.get_version.outputs.version }}.zip
          asset_name: opendsh-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip
