name: build

on:
#  schedule:
#    - cron: '0 10 * * *' # everyday at 10am

#  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - 
        name: Get the version
        id: get_version
        run: |
          echo ::set-output name=version::"${version}"
        env:
          version: ${{ github.event.inputs.version }}
      - 
        name: pi-gen config
        id: pi-gen_config
        run: |
          cat > config <<EOF
          IMG_NAME='${version}'
          FIRST_USER_NAME='opendsh'
          FIRST_USER_PASS='opendsh'
          EOF
          touch ./stage4/SKIP ./stage5/SKIP
          touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
        working-directory: ./pi-gen
        env:
          version: ${{ steps.get_version.outputs.version }}
      -
        name: opendsh
        id: opendsh
        run: |
          rm -rf ./stage3 ./stage4 ./stage5
          mkdir -p ./stage3/00-install-dash
          cd ./stage3
          cp ../stage2/prerun.sh prerun.sh
          chmod +x prerun.sh
          cat > EXPORT_IMAGE <<EOF
          IMG_SUFFIX="-opendsh"
          EOF
          cat > EXPORT_NOOBS <<EOF
          NOOBS_NAME="Opendsh (32-bit) - ${version}"
          NOOBS_DESCRIPTION="Opendsh - ${version}"
          EOF
          cat > 00-install-dash/00-packages <<EOF
          git
          EOF
          cat > 00-install-dash/00-run.sh <<EOF
          #!/bin/bash -e
          
          on_chroot << END
          echo '>>> Set Debian frontend to Noninteractive'
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
          export DEBIAN_FRONTEND=noninteractive
          echo '>>> Update CA certs for a secure connection to GitHub'
          update-ca-certificates -f
          echo '>>> Download latest Dash Installer'
          git clone --depth=1 https://github.com/openDsh/dash.git /home/${FIRST_USER_NAME}/dash
          chmod -R 775 /home/${FIRST_USER_NAME}/dash
          chown -R ${FIRST_USER_NAME}:${FIRST_USER_NAME} /home/${FIRST_USER_NAME}/dash
          END
          EOF
          chmod +x 00-install-dash/00-run.sh
          cat > 00-install-dash/01-run.sh <<EOF
          #!/bin/bash -e

          on_chroot << END
          echo "Installing Dash"
          sed 's/message( WARNING/message( /g' /home/${FIRST_USER_NAME}/dash/cmake_modules/functions.cmake
          /home/${FIRST_USER_NAME}/dash/install.sh
          END
          EOF
          chmod +x 00-install-dash/01-run.sh
          cat > 00-install-dash/02-run-chroot.sh <<EOF
          #!/bin/bash -e
          
          apt-get autoremove -y --purge
          EOF
          chmod +x 00-install-dash/02-run-chroot.sh
        working-directory: ./pi-gen
        env:
          version: ${{ steps.get_version.outputs.version }}
      -
       name: show config
       id: show_config
       run: |
          cat config
          cat ./stage3/EXPORT_NOOBS
          cat ./stage3/EXPORT_IMAGE
       working-directory: ./pi-gen
      -
        name: Run build
        id: build-docker
        run: bash ./build-docker.sh
        working-directory: ./pi-gen
      - 
        name: Upload build artifacts 
        id: upload_deploy
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: |
            ./pi-gen/deploy/*.info
            ./pi-gen/deploy/*.zip
            ./pi-gen/deploy/build.log
  release:
    needs: [build]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: true
      - 
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy
      - 
        name: Get Release File Name & Upload URL
        id: get_release_info
        run: |
          ARTIFACT_PATHNAME=$(ls deploy/*.zip | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
          echo ::set-output name=artifact_filename::${ARTIFACT_NAME}
          echo ::set-output name=artifact_path::${ARTIFACT_PATHNAME}
      - 
        name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.get-artifact-name.outputs.artifact_path }}
          asset_name: ${{ steps.get-artifact-name.outputs.artifact_filename }}
          asset_content_type: application/zip
